services:
    sftp:
        container_name: sftp_rodri
        image: atmoz/sftp
        ports:
            - "9922:22"
        command: user:password:1001:123456:/out
    postgres:
        image: postgres:15-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U homestead -d postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    kafka:
        image: apache/kafka:3.9.1
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
            KAFKA_LISTENERS: "PLAINTEXT://:29092,CONTROLLER://:29093,PLAINTEXT_HOST://:9092"
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            CLUSTER_ID: "4L4g1c1-BJV2vM4noUxExQ"